{
  "type": "record",
  "name": "FastOrderCancelledV1",
  "namespace": "fast.events.order.v1",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "eventVersion",
      "type": "int",
      "default": 1
    },
    {
      "name": "occurredAt",
      "type": "long"
    },
    {
      "name": "orderId",
      "type": "string"
    },
    {
      "name": "riderId",
      "type": "string"
    },
    {
      "name": "driverId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "actorType",
      "type": "string"
    },
    {
      "name": "actorId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "reasonCode",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}
