{
  "namespace": "br.com.hellnet.fast.events.ride.v1",
  "type": "record",
  "name": "FastRideCompletedV1",
  "doc": "Published when a ride is completed in Fast.",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "eventVersion",
      "type": "int",
      "default": 1
    },
    {
      "name": "occurredAt",
      "type": "long"
    },
    {
      "name": "rideId",
      "type": "string"
    },
    {
      "name": "riderId",
      "type": "string"
    },
    {
      "name": "driverId",
      "type": "string"
    }
  ]
}
