{
  "namespace": "fast.order.completed",
  "type": "record",
  "name": "v1",
  "aliases": ["fast.events.order.v1.FastOrderCompletedV1"],
  "doc": "Published when an order is completed in Fast.",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "eventVersion",
      "type": "int",
      "default": 1
    },
    {
      "name": "occurredAt",
      "type": "long"
    },
    {
      "name": "orderId",
      "type": "string"
    },
    {
      "name": "riderId",
      "type": "string"
    },
    {
      "name": "driverId",
      "type": "string"
    }
  ]
}
